
const employees = [
  {
    id: 1,
    name: "Arjun Sharma",
    email: "arjun.sharma@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 0,
      complete: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Design Login Page",
        taskDescription: "Create a responsive login form using Tailwind CSS.",
        taskDate: "2025-04-16",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Resolve dropdown issue on mobile view.",
        taskDate: "2025-04-17",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        complete: true,
        failed: false,
        taskTitle: "Create Footer",
        taskDescription: "Develop the footer component with social links.",
        taskDate: "2025-04-10",
        category: "Design",
      },
    ],
  },
  {
    id: 2,
    name: "Sneha Verma",
    email: "sneha.verma@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: false,
        newTask: false,
        complete: false,
        failed: true,
        taskTitle: "Setup CI/CD",
        taskDescription: "Configure GitHub Actions for auto deployment.",
        taskDate: "2025-04-14",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "API Integration",
        taskDescription: "Integrate backend APIs with the frontend.",
        taskDate: "2025-04-16",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Testing Routes",
        taskDescription: "Unit test all API routes for user module.",
        taskDate: "2025-04-18",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        complete: true,
        failed: false,
        taskTitle: "Wireframe Dashboard",
        taskDescription: "Design the dashboard wireframe in Figma.",
        taskDate: "2025-04-11",
        category: "Design",
      },
    ],
  },
  {
    id: 3,
    name: "Rahul Mehra",
    email: "rahul.mehra@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      complete: 1,
      failed: 0,
    },
    tasks: [
      {
        active: false,
        newTask: false,
        complete: true,
        failed: false,
        taskTitle: "Update Dependencies",
        taskDescription: "Upgrade outdated packages in package.json.",
        taskDate: "2025-04-12",
        category: "Maintenance",
      },
      {
        active: true,
        newTask: true,
        complete: false,
        failed: false,
        taskTitle: "Implement Dark Mode",
        taskDescription: "Add dark mode toggle using Tailwind CSS.",
        taskDate: "2025-04-15",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Clean Codebase",
        taskDescription: "Remove unused imports and comments.",
        taskDate: "2025-04-16",
        category: "Refactoring",
      },
    ],
  },
  {
    id: 4,
    name: "Priya Kapoor",
    email: "priya.kapoor@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        complete: false,
        failed: false,
        taskTitle: "Bug Triage",
        taskDescription: "Review and prioritize bug reports.",
        taskDate: "2025-04-17",
        category: "QA",
      },
      {
        active: false,
        newTask: false,
        complete: true,
        failed: false,
        taskTitle: "Style About Page",
        taskDescription: "Polish the styling for the About Us page.",
        taskDate: "2025-04-14",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        complete: false,
        failed: true,
        taskTitle: "Deploy Backend",
        taskDescription: "Deployment to production failed due to server error.",
        taskDate: "2025-04-13",
        category: "Deployment",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Accessibility Audit",
        taskDescription:
          "Test for screen reader support and keyboard navigation.",
        taskDate: "2025-04-18",
        category: "Testing",
      },
    ],
  },
  {
    id: 5,
    name: "Amit Patel",
    email: "amit.patel@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      complete: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        complete: false,
        failed: false,
        taskTitle: "Onboarding Flow",
        taskDescription: "Design and implement new user onboarding screens.",
        taskDate: "2025-04-17",
        category: "UX",
      },
      {
        active: false,
        newTask: false,
        complete: true,
        failed: false,
        taskTitle: "Fix Responsiveness",
        taskDescription:
          "Make the app responsive on tablet and mobile devices.",
        taskDate: "2025-04-15",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        complete: false,
        failed: true,
        taskTitle: "Data Migration",
        taskDescription: "Failed to migrate user data from v1.",
        taskDate: "2025-04-10",
        category: "Database",
      },
      {
        active: true,
        newTask: false,
        complete: false,
        failed: false,
        taskTitle: "Weekly Report",
        taskDescription: "Prepare team progress report for the week.",
        taskDate: "2025-04-19",
        category: "Management",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    name: "Harsh Jat",
    email: "harsh@jat.com",
    password: 123,
  },
];

export const setLocalStorage = ()=>{
  localStorage.setItem("employees" , JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return {employees, admin};
}
